<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entities\s0wfn3eq.ml2~" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdKartShared\AdKartShared.csproj" />
  </ItemGroup>

</Project>
